#!/usr/bin/env python

import sys
sys.path.append('/home/bruno/repository/pinpeople/event_people_python/')

from event_people.emitter import Emitter
from event_people.event import Event
import os

os.environ["RABBIT_URL"] = "amqp://guest:guest@localhost:5672"
os.environ['RABBIT_EVENT_PEOPLE_APP_NAME'] = 'EventPeopleExampleApp'
os.environ['RABBIT_EVENT_PEOPLE_VHOST'] = 'event_people'
os.environ['RABBIT_EVENT_PEOPLE_TOPIC_NAME'] = 'topic1'


body = {'text': 'meu chefe é legal'}
e1 = Event(name='resource.origin.action.all', body=body, appName='EventPeopleExampleApp')

Emitter.trigger(e1)
