#!/usr/bin/env python
import sys
import os
import json

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from event_people.listener import Listener
from event_people.event import Event

os.environ["RABBIT_URL"] = "amqp://guest:guest@localhost:5672"
os.environ['RABBIT_EVENT_PEOPLE_APP_NAME'] = 'EventPeopleExampleApp'
os.environ['RABBIT_EVENT_PEOPLE_VHOST'] = 'event_people'
os.environ['RABBIT_EVENT_PEOPLE_TOPIC_NAME'] = 'topic1'

result = None
def callback_test(ch, method, properties, body) -> Event:
        print(" [x] %r:%r" % (method.routing_key, body))
        json_message = json.loads(body)
        header = json_message['header']
        name = header['resource'] + '.' + header['origin'] +  '.'  + header['action'] + '.' + header['destiny']
        result = Event(appName=header['app'], name=name ,body=json_message['body'])
        ch.basic_ack(delivery_tag= method.delivery_tag)


Listener.on(callback_test,'resource.origin.action.all', 'resource.origin1.action2.all')
