#!/usr/bin/env python
import sys

sys.path.append('/home/bruno/repository/pinpeople/event_people_python/')

from src.listener import Listener



Listener.on('resource.*.action', 'resource.*.action2')

