#!/usr/bin/env python

import sys
sys.path.append('/home/bruno/repository/pinpeople/event_people_python/')

from src.emitter import Emitter
from src.event import Event

events = []

body = {'text': 'meu chefe é legal'}
e1 = Event(name='resource.origin.action', body=body, appName='EventPeopleExampleApp')
events.append(e1)

body= {'text': 'a empresa que eu trabalho é ótima'}
e2 = Event(name='resource.origin1.action2', body=body, appName='EventPeopleExampleApp')
events.append(e2)

Emitter.trigger(events)
