#!/usr/bin/env python
import sys
import os

sys.path.append('/home/bruno/repository/pinpeople/event_people_python/')

from event_people.listener import Listener

os.environ["RABBIT_URL"] = "amqp://guest:guest@localhost:5672"
os.environ['RABBIT_EVENT_PEOPLE_APP_NAME'] = 'EventPeopleExampleApp'
os.environ['RABBIT_EVENT_PEOPLE_VHOST'] = 'event_people'
os.environ['RABBIT_EVENT_PEOPLE_TOPIC_NAME'] = 'topic1'


Listener.on('resource.*.action')

